### ISSUE TITLE
S3 bucket lifecycle

### ISSUE THREAD

**Issue by Halama** [keboola/aws-cloudtrail-slack-hook#2]
Nastavil bych jako parametr CF template a na produkci nastavil alespon na 1 rok?

https://github.com/keboola/aws-cloudtrail-slack-hook/blob/655c7e69fa1a2e74cada603c0037c95eb66a0ece/cf-stack.json#L393

**Comment by Halama** [comment]
Nebo bych to možná neexpiroval vůbec, doteď jsme to taky neexpirovali.

**Comment by JakubMatejka** [comment]
Jasně, expiraci vypínám.

**Comment by Halama** [comment]
Já myslel že to upravíš v té CF template.

**Comment by JakubMatejka** [comment]
jj: https://github.com/keboola/aws-cloudtrail-slack-hook/commit/5fbea900a62db1e6a1a6de08c76e1c6954228fc2

**Comment by Halama** [comment]
aha, sorry minul jsem ten commit:)

**Comment by JakubMatejka** [comment]
Já jsem to tak trošku zapomněl vzít přes PR 🙄

**Comment by Halama** [comment]
OMG, až teď jsem si všimnul že jsem předtím nalinkoval serverless deploy s3 bucket. Šlo mi samozřejmě o bucket ve kterém leží ty traily. Dnes jsem ho kontroloval na prod a překvapilo mě že tam je 7 dní.
https://github.com/keboola/aws-cloudtrail-slack-hook/blob/655c7e69fa1a2e74cada603c0037c95eb66a0ece/serverless.yml#L84
Pošlu PR

**Comment by JakubMatejka** [comment]
OMG. ;o) Ok, ale přidal jsem ti do toho PR vrácení expirace toho deploy bucketu, ať to tam zbytečně netrčí.

**Comment by Halama** [comment]
jo jasně
